/*
 * SearchModuleXMLReader.java
 * Created on 2013/06/28
 *
 * Copyright (C) 2011-2013 Nippon Telegraph and Telephone Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package tubame.knowhow.biz.logic.io;

import java.io.IOException;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;

import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import javax.xml.parsers.ParserConfigurationException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.xml.sax.SAXException;

import tubame.knowhow.biz.exception.JbmException;
import tubame.knowhow.biz.model.generated.python.PortabilitySearchModule;
import tubame.knowhow.biz.util.JaxbUtil;
import tubame.knowhow.biz.util.resource.ApplicationPropertiesUtil;
import tubame.knowhow.biz.util.resource.MessagePropertiesUtil;

/**
 * The use of the object that is automatically generated by JAXB, <br/>
 * reading process of information search module XML file.<br/>
 * To read the information search module XML file in Unmarshaller method of
 * JAXB,<br/>
 * get PortabilitySearchModule object.<br/>
 */
public class SearchModuleXMLReader implements SearchModuleRead {

    /** Logger */
    private static final Logger LOGGER = LoggerFactory
            .getLogger(SearchModuleXMLReader.class);

    /**
     * {@inheritDoc}
     */
    @Override
    public PortabilitySearchModule read(String filePath) throws JbmException {
        LOGGER.debug("[PortabilitySearchModuleFilePath]=" + filePath);
        // Getting path from resource
        URL url = getUrl(filePath);
        if (url == null) {
            throw new JbmException(
                    MessagePropertiesUtil
                            .getMessage(MessagePropertiesUtil.FAIL_READ_SEARCH_MODULE),
                    null);
        }
        PortabilitySearchModule searchModule = new PortabilitySearchModule();
        Map<String, Integer> errMap = new HashMap<String, Integer>();
        try {
            LOGGER.trace(MessagePropertiesUtil
                    .getMessage(MessagePropertiesUtil.LOG_START_SEARCH_MODULE_READER));
            // Generation of Anne marshaller
            Unmarshaller unmarshaller = JaxbUtil
                    .getUnmarshaller(
                            PortabilitySearchModule.class,
                            ApplicationPropertiesUtil
                                    .getProperty(ApplicationPropertiesUtil.PYTHONMODULEDEFINITIONSCHEMA_PATH),
                            errMap);

            // Set to PortabilitySearchModule the contents of the search module
            // XML information read
            searchModule = (PortabilitySearchModule) unmarshaller
                    .unmarshal(NonDTDCheckEntityResolver.createDocument(
                            url.getFile(),
                            ApplicationPropertiesUtil
                                    .getProperty(ApplicationPropertiesUtil.SEARCHMODULE_ENCODE)));
            LOGGER.trace(MessagePropertiesUtil
                    .getMessage(MessagePropertiesUtil.LOG_STOP_SEARCH_MODULE_READER));
        } catch (JAXBException e) {
            LOGGER.error(MessagePropertiesUtil
                    .getMessage(MessagePropertiesUtil.FAIL_READ_SEARCH_MODULE),
                    e);
            LOGGER.error("[FilePath]=" + filePath);
            String errMessage = JaxbUtil
                    .getUnmarshalErrorMessage(
                            MessagePropertiesUtil
                                    .getMessage(MessagePropertiesUtil.FAIL_READ_SEARCH_MODULE),
                            errMap);
            throw new JbmException(errMessage, e);
        } catch (IOException e) {
            throw createJbmException(
                    filePath,
                    MessagePropertiesUtil
                            .getMessage(MessagePropertiesUtil.FAIL_READ_SEARCH_MODULE),
                    e);
        } catch (ParserConfigurationException e) {
            throw createJbmException(
                    filePath,
                    MessagePropertiesUtil
                            .getMessage(MessagePropertiesUtil.FAIL_READ_SEARCH_MODULE),
                    e);
        } catch (IllegalArgumentException e) {
            throw createJbmException(
                    filePath,
                    MessagePropertiesUtil
                            .getMessage(MessagePropertiesUtil.FAIL_READ_SEARCH_MODULE),
                    e);
        } catch (SAXException e) {
            throw createJbmExceptionJaxBInformation(
                    filePath,
                    MessagePropertiesUtil
                            .getMessage(MessagePropertiesUtil.FAIL_READ_SEARCH_MODULE),
                    e, errMap);
        }
        return searchModule;
    }

    /**
     * Create JbmException.<br/>
     * 
     * @param filePath
     *            Target file path
     * @param message
     *            Error message
     * @param e
     *            Exception information
     * @return JbmException that is generated
     */
    protected JbmException createJbmException(String filePath, String message,
            Exception e) {
        LOGGER.error("[FilePath]=" + filePath);
        LOGGER.error(MessagePropertiesUtil.getMessage(message), e);
        return new JbmException(MessagePropertiesUtil.getMessage(message), e);
    }

    /**
     * Generate JbmException.<br/>
     * 
     * @param filePath
     *            Target file path
     * @param message
     *            Error message
     * @param e
     *            Exception information
     * @param errorMap
     *            Check the contents
     * @return JbmException that is generated
     */
    protected JbmException createJbmExceptionJaxBInformation(String filePath,
            String message, Exception e, Map<String, Integer> errorMap) {
        LOGGER.error("[FilePath]=" + filePath);
        LOGGER.error(MessagePropertiesUtil.getMessage(message), e);
        String errMessage = JaxbUtil.getUnmarshalErrorMessage(
                MessagePropertiesUtil.getMessage(message), errorMap);
        return new JbmException(errMessage, e);
    }

    /**
     * Get a file URL.<br/>
     * 
     * @param filepath
     *            File Path
     * @return url
     */
    protected URL getUrl(String filepath) {
        return this.getClass().getResource(filepath);
    }
}
